name: Stale
on:
  schedule:
  - cron: '32 22 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: 90 days stale policy
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          days-before-close: 7
          operations-per-run: 25
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale,help%20wanted"
          stale-issue-message: >
            There hasn't been any activity on this issue recently. We have to clean 
            some of the old issues, as many of them have already been resolved with
            the latest Lutris Wine versions.
            Please make sure to update to the latest Lutris Wine version and
            check if that solves the issue. Let us know if that works for you by
            adding a comment 👍
            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.
            Thank you for your contributions.
